### ISSUE TITLE
Error and exception when running on a fresh and (almost) empty repository.

### ISSUE THREAD

**Issue by jenstroeger** [liran-funaro/sphinx-markdown-builder#2]
**Describe the bug**

I tried using the package on [this Python Package Template repo](https://github.com/jenstroeger/python-package-template) (to replace the existing Markdown builder) and generating docs fails in two ways:

 - if no `docs/_build/markdown/index.md` file pre-exists then I get a warning ([run](https://github.com/jenstroeger/python-package-template/actions/runs/5630279003/job/15256111166?pr=585#step:9:186))
    ```
    [Errno 2] No such file or directory: '/home/runner/work/python-package-template/python-package-template/docs/_build/markdown/index.md'
    ```
 - if there’s not much content (like is the case for that repo) then this assertion fires ([run](https://github.com/jenstroeger/python-package-template/actions/runs/5630279003/job/15256111166?pr=585#step:9:196))
   ```
     Exception occurred:
     File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/sphinx_markdown_builder/contexts.py", line 256, in make
       assert len(content) > 0, "Empty table"
   AssertionError: Empty table
   ```

**To Reproduce**

Check out the repository on branch `try-sphinx-markdown-builder` for PR https://github.com/jenstroeger/python-package-template/pull/585, and then
```bash
make venv
. .venv/bin/activate
make setup
make docs  # This will fail.
```
The last command will fail with the above errors.

**Expected behavior**

That last command should build the markdown docs.

**Enviroment (please complete the following information):**

 - OS: macOS
 - Version: 13.4

**Additional context**

n/a

**Comment by liran-funaro** [comment]
@jenstroeger First of all, thank you for taking the time to report the issue you encountered. Your contribution is truly appreciated!

I'm pleased to inform you that I've addressed the bug and released a new version  ([v0.6.4](https://pypi.org/project/sphinx-markdown-builder/0.6.4)) on PyPI. Kindly update to the latest release and let me know if it resolves the problem on your end.

If the issue is now resolved, I would be grateful if you could close the GitHub issue. Your feedback helps us maintain and improve the package for everyone.

Once again, thank you for your valuable input!

**Comment by jenstroeger** [comment]
Thanks @liran-funaro for the swift fix, and thank you for picking up this Sphinx Markdown package — I look forward to seeing it evolve into generating better Markdown 🤓

I updated to the latest release and all tests pass now: https://github.com/jenstroeger/python-package-template/pull/585

One slightly misleading message, however, is
```
writing output... 
WARNING: error accessing file /path/to/python-package-template/docs/_build/markdown/index.md: [Errno 2] No such file or directory: '/path/to/python-package-template/docs/_build/markdown/index.md'
```
but I’m not sure if this comes from Sphinx or from the Markdown extension.

<hr>

For context: in the [Package Template](https://github.com/jenstroeger/python-package-template) I use that Markdown plugin to automatically generate the Wiki for that repo ([link](https://github.com/jenstroeger/python-package-template/wiki)) and there are a few things where the Markdown could be improved — are you interested in feedback?

**Comment by liran-funaro** [comment]
>One slightly misleading message [...]

It is indeed misleading. It was a mistake in my code.
I fixed it in the latest commit. Since it is a low severity, I'll postpone the release until higher severity changes are applied.

>[...] there are a few things where the Markdown could be improved — are you interested in feedback?

I'm very interested in feedback. Please feel free to open issues/PRs.

My unit tests are lacking, so any contribution will be highly appreciated.
I believe that suggesting changes to the unit tests as a PR better reflects your contribution to this project.

Please check out the unit tests folders: [tests/source](/liran-funaro/sphinx-markdown-builder/tree/main/tests/source) and [tests/expected](/liran-funaro/sphinx-markdown-builder/tree/main/tests/expected).
You are encouraged to suggest improvements or additions to these unit tests to capture relevant use cases.

**Comment by liran-funaro** [comment]
@jenstroeger 

I've added an issue template for a discrepancy report.

The discrepancy report allows for quick reporting of issues with the generated output.
For example, missing line breaks, wrong format, etc.

If you have time and wish your contribution to be better reflected in the project, consider opening a PR that improves, fixes, or adds tests. This is instead or in addition to opening an issue.
For more information, see [Contributing Tests](/liran-funaro/sphinx-markdown-builder/tree/main/CONTRIBUTING.md#contributing-tests).

**Comment by jenstroeger** [comment]
Thank @liran-funaro for the fix [above](https://github.com/liran-funaro/sphinx-markdown-builder/issues/2#issuecomment-1646826520) and for all the additional information, will do!

For now, let me close this PR as completed 👍🏼
